# - path: 
#   - /grab
#   controller: Controllers\TransferController::grabFile

- path: 
  - /add
  controller: Controllers\TransferController::add

- path: 
  - /download/(\d+)
  controller: Controllers\TransferController::download
  
- path:
    - 
  controller: Controllers\TransferController::index

